### PR TITLE
change banner for 2018

### PR DESCRIPTION
**Pull request by labbydev**
Update the banner with 2018 and the dates and change the background to be something with less white guys. 

#### Includes
* https://github.com/orgs/MidCamp/projects/1#card-4864930
* https://github.com/MidCamp/midcamp/issues/44

#### Testing instructions
* checkout branch
* `npm run butler`
* Navigate to Homepage (http://localhost:4000/home)
* Observe the banner is using the drop background image

##### Remaining tasks
* [ ] Set card to done
* [ ] Comment (and close) issue

### CODE REVIEW

**Comment by froboy** [comment]
@labbydev I'm not having luck getting this to compile... I pulled down the repo, `npm install`'ed, then:

```
$ npm run butler

> hatter@1.0.0 butler /Users/aschwab/Sites/Hatter
> node_modules/butler/node_modules/.bin/gulp --gulpfile node_modules/butler/Gulpfile.js

[10:27:26] Working directory changed to ~/Sites/Hatter/node_modules/butler
[10:27:28] Using gulpfile ~/Sites/Hatter/node_modules/butler/Gulpfile.js
[10:27:28] Starting 'sass'...
Running Sass and PostCSS...
[10:27:28] Starting 'spress-watch'...
[10:27:28] Finished 'spress-watch' after 23 ms
[10:27:28] Starting 'watch'...
[10:27:28] Finished 'watch' after 13 ms
[10:27:30] Finished 'sass' after 2.1 s
[10:27:30] Starting 'spress-serve'...
[10:27:30] 'spress-serve' errored after 89 ms
[10:27:30] Error in plugin 'gulp-exec'
Message:
    Command failed: ../../vendor/bin/spress site:build --server --source=../../
/bin/sh: ../../vendor/bin/spress: No such file or directory

Details:
    killed: false
    code: 127
    signal: null
    cmd: ../../vendor/bin/spress site:build --server --source=../../
File /Users/aschwab/Sites/Hatter/src/content/assets/css/ was added, updating spress...
[10:27:30] Starting 'spress-build'...
[10:27:30] 'spress-build' errored after 10 ms
[10:27:30] Error in plugin 'gulp-exec'
Message:
    Command failed: ../../vendor/bin/spress site:build --source=../../
/bin/sh: ../../vendor/bin/spress: No such file or directory

Details:
    killed: false
    code: 127
    signal: null
    cmd: ../../vendor/bin/spress site:build --source=../../
```

**Comment by labbydev** [comment]
@froboy did you run `composer install` before trying to run `npm run butler`? It looks like you're missing spress.

**Comment by froboy** [comment]
D'oh. Didn't realize I needed npm and composer install...

**Comment by froboy** [comment]
LGTM. I ran the image through a compressor and cut the file size down by around 50% with no real loss in quality.

**Pull request merged**
